/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PressureWashingIndexRouteImport } from './routes/pressure-washing/index'
import { Route as GutterCleaningIndexRouteImport } from './routes/gutter-cleaning/index'
import { Route as PressureWashingTorontoRouteImport } from './routes/pressure-washing/toronto'
import { Route as PressureWashingMississaugaRouteImport } from './routes/pressure-washing/mississauga'
import { Route as PressureWashingMarkhamRouteImport } from './routes/pressure-washing/markham'
import { Route as GutterCleaningTorontoRouteImport } from './routes/gutter-cleaning/toronto'
import { Route as GutterCleaningMississaugaRouteImport } from './routes/gutter-cleaning/mississauga'
import { Route as GutterCleaningMarkhamRouteImport } from './routes/gutter-cleaning/markham'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingIndexRoute = PressureWashingIndexRouteImport.update({
  id: '/pressure-washing/',
  path: '/pressure-washing/',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningIndexRoute = GutterCleaningIndexRouteImport.update({
  id: '/gutter-cleaning/',
  path: '/gutter-cleaning/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingTorontoRoute = PressureWashingTorontoRouteImport.update({
  id: '/pressure-washing/toronto',
  path: '/pressure-washing/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingMississaugaRoute =
  PressureWashingMississaugaRouteImport.update({
    id: '/pressure-washing/mississauga',
    path: '/pressure-washing/mississauga',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressureWashingMarkhamRoute = PressureWashingMarkhamRouteImport.update({
  id: '/pressure-washing/markham',
  path: '/pressure-washing/markham',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningTorontoRoute = GutterCleaningTorontoRouteImport.update({
  id: '/gutter-cleaning/toronto',
  path: '/gutter-cleaning/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningMississaugaRoute =
  GutterCleaningMississaugaRouteImport.update({
    id: '/gutter-cleaning/mississauga',
    path: '/gutter-cleaning/mississauga',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningMarkhamRoute = GutterCleaningMarkhamRouteImport.update({
  id: '/gutter-cleaning/markham',
  path: '/gutter-cleaning/markham',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning/': typeof GutterCleaningIndexRoute
  '/pressure-washing/': typeof PressureWashingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning': typeof GutterCleaningIndexRoute
  '/pressure-washing': typeof PressureWashingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning/': typeof GutterCleaningIndexRoute
  '/pressure-washing/': typeof PressureWashingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning/'
    | '/pressure-washing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning'
    | '/pressure-washing'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning/'
    | '/pressure-washing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GutterCleaningMarkhamRoute: typeof GutterCleaningMarkhamRoute
  GutterCleaningMississaugaRoute: typeof GutterCleaningMississaugaRoute
  GutterCleaningTorontoRoute: typeof GutterCleaningTorontoRoute
  PressureWashingMarkhamRoute: typeof PressureWashingMarkhamRoute
  PressureWashingMississaugaRoute: typeof PressureWashingMississaugaRoute
  PressureWashingTorontoRoute: typeof PressureWashingTorontoRoute
  GutterCleaningIndexRoute: typeof GutterCleaningIndexRoute
  PressureWashingIndexRoute: typeof PressureWashingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/': {
      id: '/pressure-washing/'
      path: '/pressure-washing'
      fullPath: '/pressure-washing/'
      preLoaderRoute: typeof PressureWashingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/': {
      id: '/gutter-cleaning/'
      path: '/gutter-cleaning'
      fullPath: '/gutter-cleaning/'
      preLoaderRoute: typeof GutterCleaningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/toronto': {
      id: '/pressure-washing/toronto'
      path: '/pressure-washing/toronto'
      fullPath: '/pressure-washing/toronto'
      preLoaderRoute: typeof PressureWashingTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/mississauga': {
      id: '/pressure-washing/mississauga'
      path: '/pressure-washing/mississauga'
      fullPath: '/pressure-washing/mississauga'
      preLoaderRoute: typeof PressureWashingMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/markham': {
      id: '/pressure-washing/markham'
      path: '/pressure-washing/markham'
      fullPath: '/pressure-washing/markham'
      preLoaderRoute: typeof PressureWashingMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/toronto': {
      id: '/gutter-cleaning/toronto'
      path: '/gutter-cleaning/toronto'
      fullPath: '/gutter-cleaning/toronto'
      preLoaderRoute: typeof GutterCleaningTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/mississauga': {
      id: '/gutter-cleaning/mississauga'
      path: '/gutter-cleaning/mississauga'
      fullPath: '/gutter-cleaning/mississauga'
      preLoaderRoute: typeof GutterCleaningMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/markham': {
      id: '/gutter-cleaning/markham'
      path: '/gutter-cleaning/markham'
      fullPath: '/gutter-cleaning/markham'
      preLoaderRoute: typeof GutterCleaningMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GutterCleaningMarkhamRoute: GutterCleaningMarkhamRoute,
  GutterCleaningMississaugaRoute: GutterCleaningMississaugaRoute,
  GutterCleaningTorontoRoute: GutterCleaningTorontoRoute,
  PressureWashingMarkhamRoute: PressureWashingMarkhamRoute,
  PressureWashingMississaugaRoute: PressureWashingMississaugaRoute,
  PressureWashingTorontoRoute: PressureWashingTorontoRoute,
  GutterCleaningIndexRoute: GutterCleaningIndexRoute,
  PressureWashingIndexRoute: PressureWashingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
