/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GutterCleaningTorontoRouteImport } from './routes/gutter-cleaning-toronto'
import { Route as GutterCleaningMississaugaRouteImport } from './routes/gutter-cleaning-mississauga'
import { Route as GutterCleaningMarkhamRouteImport } from './routes/gutter-cleaning-markham'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningTorontoRoute = GutterCleaningTorontoRouteImport.update({
  id: '/gutter-cleaning-toronto',
  path: '/gutter-cleaning-toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningMississaugaRoute =
  GutterCleaningMississaugaRouteImport.update({
    id: '/gutter-cleaning-mississauga',
    path: '/gutter-cleaning-mississauga',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningMarkhamRoute = GutterCleaningMarkhamRouteImport.update({
  id: '/gutter-cleaning-markham',
  path: '/gutter-cleaning-markham',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gutter-cleaning-markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning-mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning-toronto': typeof GutterCleaningTorontoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gutter-cleaning-markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning-mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning-toronto': typeof GutterCleaningTorontoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gutter-cleaning-markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning-mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning-toronto': typeof GutterCleaningTorontoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gutter-cleaning-markham'
    | '/gutter-cleaning-mississauga'
    | '/gutter-cleaning-toronto'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gutter-cleaning-markham'
    | '/gutter-cleaning-mississauga'
    | '/gutter-cleaning-toronto'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gutter-cleaning-markham'
    | '/gutter-cleaning-mississauga'
    | '/gutter-cleaning-toronto'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GutterCleaningMarkhamRoute: typeof GutterCleaningMarkhamRoute
  GutterCleaningMississaugaRoute: typeof GutterCleaningMississaugaRoute
  GutterCleaningTorontoRoute: typeof GutterCleaningTorontoRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning-toronto': {
      id: '/gutter-cleaning-toronto'
      path: '/gutter-cleaning-toronto'
      fullPath: '/gutter-cleaning-toronto'
      preLoaderRoute: typeof GutterCleaningTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning-mississauga': {
      id: '/gutter-cleaning-mississauga'
      path: '/gutter-cleaning-mississauga'
      fullPath: '/gutter-cleaning-mississauga'
      preLoaderRoute: typeof GutterCleaningMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning-markham': {
      id: '/gutter-cleaning-markham'
      path: '/gutter-cleaning-markham'
      fullPath: '/gutter-cleaning-markham'
      preLoaderRoute: typeof GutterCleaningMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GutterCleaningMarkhamRoute: GutterCleaningMarkhamRoute,
  GutterCleaningMississaugaRoute: GutterCleaningMississaugaRoute,
  GutterCleaningTorontoRoute: GutterCleaningTorontoRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
