/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PressureWashingIndexRouteImport } from './routes/pressure-washing/index'
import { Route as JunkRemovalIndexRouteImport } from './routes/junk-removal/index'
import { Route as GutterCleaningIndexRouteImport } from './routes/gutter-cleaning/index'
import { Route as PressureWashingTorontoRouteImport } from './routes/pressure-washing/toronto'
import { Route as PressureWashingMississaugaRouteImport } from './routes/pressure-washing/mississauga'
import { Route as PressureWashingMarkhamRouteImport } from './routes/pressure-washing/markham'
import { Route as JunkRemovalTorontoRouteImport } from './routes/junk-removal/toronto'
import { Route as JunkRemovalMississaugaRouteImport } from './routes/junk-removal/mississauga'
import { Route as JunkRemovalMarkhamRouteImport } from './routes/junk-removal/markham'
import { Route as GutterCleaningWhitbyRouteImport } from './routes/gutter-cleaning/whitby'
import { Route as GutterCleaningVaughanRouteImport } from './routes/gutter-cleaning/vaughan'
import { Route as GutterCleaningTorontoRouteImport } from './routes/gutter-cleaning/toronto'
import { Route as GutterCleaningScarboroughRouteImport } from './routes/gutter-cleaning/scarborough'
import { Route as GutterCleaningRichmondHillRouteImport } from './routes/gutter-cleaning/richmond-hill'
import { Route as GutterCleaningPickeringRouteImport } from './routes/gutter-cleaning/pickering'
import { Route as GutterCleaningOshawaRouteImport } from './routes/gutter-cleaning/oshawa'
import { Route as GutterCleaningOakvilleRouteImport } from './routes/gutter-cleaning/oakville'
import { Route as GutterCleaningNorthYorkRouteImport } from './routes/gutter-cleaning/north-york'
import { Route as GutterCleaningMississaugaRouteImport } from './routes/gutter-cleaning/mississauga'
import { Route as GutterCleaningMarkhamRouteImport } from './routes/gutter-cleaning/markham'
import { Route as GutterCleaningEtobicokeRouteImport } from './routes/gutter-cleaning/etobicoke'
import { Route as GutterCleaningBurlingtonRouteImport } from './routes/gutter-cleaning/burlington'
import { Route as GutterCleaningBramptonRouteImport } from './routes/gutter-cleaning/brampton'
import { Route as GutterCleaningAjaxRouteImport } from './routes/gutter-cleaning/ajax'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingIndexRoute = PressureWashingIndexRouteImport.update({
  id: '/pressure-washing/',
  path: '/pressure-washing/',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkRemovalIndexRoute = JunkRemovalIndexRouteImport.update({
  id: '/junk-removal/',
  path: '/junk-removal/',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningIndexRoute = GutterCleaningIndexRouteImport.update({
  id: '/gutter-cleaning/',
  path: '/gutter-cleaning/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingTorontoRoute = PressureWashingTorontoRouteImport.update({
  id: '/pressure-washing/toronto',
  path: '/pressure-washing/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingMississaugaRoute =
  PressureWashingMississaugaRouteImport.update({
    id: '/pressure-washing/mississauga',
    path: '/pressure-washing/mississauga',
    getParentRoute: () => rootRouteImport,
  } as any)
const PressureWashingMarkhamRoute = PressureWashingMarkhamRouteImport.update({
  id: '/pressure-washing/markham',
  path: '/pressure-washing/markham',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkRemovalTorontoRoute = JunkRemovalTorontoRouteImport.update({
  id: '/junk-removal/toronto',
  path: '/junk-removal/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkRemovalMississaugaRoute = JunkRemovalMississaugaRouteImport.update({
  id: '/junk-removal/mississauga',
  path: '/junk-removal/mississauga',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkRemovalMarkhamRoute = JunkRemovalMarkhamRouteImport.update({
  id: '/junk-removal/markham',
  path: '/junk-removal/markham',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningWhitbyRoute = GutterCleaningWhitbyRouteImport.update({
  id: '/gutter-cleaning/whitby',
  path: '/gutter-cleaning/whitby',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningVaughanRoute = GutterCleaningVaughanRouteImport.update({
  id: '/gutter-cleaning/vaughan',
  path: '/gutter-cleaning/vaughan',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningTorontoRoute = GutterCleaningTorontoRouteImport.update({
  id: '/gutter-cleaning/toronto',
  path: '/gutter-cleaning/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningScarboroughRoute =
  GutterCleaningScarboroughRouteImport.update({
    id: '/gutter-cleaning/scarborough',
    path: '/gutter-cleaning/scarborough',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningRichmondHillRoute =
  GutterCleaningRichmondHillRouteImport.update({
    id: '/gutter-cleaning/richmond-hill',
    path: '/gutter-cleaning/richmond-hill',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningPickeringRoute = GutterCleaningPickeringRouteImport.update({
  id: '/gutter-cleaning/pickering',
  path: '/gutter-cleaning/pickering',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningOshawaRoute = GutterCleaningOshawaRouteImport.update({
  id: '/gutter-cleaning/oshawa',
  path: '/gutter-cleaning/oshawa',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningOakvilleRoute = GutterCleaningOakvilleRouteImport.update({
  id: '/gutter-cleaning/oakville',
  path: '/gutter-cleaning/oakville',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningNorthYorkRoute = GutterCleaningNorthYorkRouteImport.update({
  id: '/gutter-cleaning/north-york',
  path: '/gutter-cleaning/north-york',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningMississaugaRoute =
  GutterCleaningMississaugaRouteImport.update({
    id: '/gutter-cleaning/mississauga',
    path: '/gutter-cleaning/mississauga',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningMarkhamRoute = GutterCleaningMarkhamRouteImport.update({
  id: '/gutter-cleaning/markham',
  path: '/gutter-cleaning/markham',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningEtobicokeRoute = GutterCleaningEtobicokeRouteImport.update({
  id: '/gutter-cleaning/etobicoke',
  path: '/gutter-cleaning/etobicoke',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningBurlingtonRoute =
  GutterCleaningBurlingtonRouteImport.update({
    id: '/gutter-cleaning/burlington',
    path: '/gutter-cleaning/burlington',
    getParentRoute: () => rootRouteImport,
  } as any)
const GutterCleaningBramptonRoute = GutterCleaningBramptonRouteImport.update({
  id: '/gutter-cleaning/brampton',
  path: '/gutter-cleaning/brampton',
  getParentRoute: () => rootRouteImport,
} as any)
const GutterCleaningAjaxRoute = GutterCleaningAjaxRouteImport.update({
  id: '/gutter-cleaning/ajax',
  path: '/gutter-cleaning/ajax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/ajax': typeof GutterCleaningAjaxRoute
  '/gutter-cleaning/brampton': typeof GutterCleaningBramptonRoute
  '/gutter-cleaning/burlington': typeof GutterCleaningBurlingtonRoute
  '/gutter-cleaning/etobicoke': typeof GutterCleaningEtobicokeRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/north-york': typeof GutterCleaningNorthYorkRoute
  '/gutter-cleaning/oakville': typeof GutterCleaningOakvilleRoute
  '/gutter-cleaning/oshawa': typeof GutterCleaningOshawaRoute
  '/gutter-cleaning/pickering': typeof GutterCleaningPickeringRoute
  '/gutter-cleaning/richmond-hill': typeof GutterCleaningRichmondHillRoute
  '/gutter-cleaning/scarborough': typeof GutterCleaningScarboroughRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/gutter-cleaning/vaughan': typeof GutterCleaningVaughanRoute
  '/gutter-cleaning/whitby': typeof GutterCleaningWhitbyRoute
  '/junk-removal/markham': typeof JunkRemovalMarkhamRoute
  '/junk-removal/mississauga': typeof JunkRemovalMississaugaRoute
  '/junk-removal/toronto': typeof JunkRemovalTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning/': typeof GutterCleaningIndexRoute
  '/junk-removal/': typeof JunkRemovalIndexRoute
  '/pressure-washing/': typeof PressureWashingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/ajax': typeof GutterCleaningAjaxRoute
  '/gutter-cleaning/brampton': typeof GutterCleaningBramptonRoute
  '/gutter-cleaning/burlington': typeof GutterCleaningBurlingtonRoute
  '/gutter-cleaning/etobicoke': typeof GutterCleaningEtobicokeRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/north-york': typeof GutterCleaningNorthYorkRoute
  '/gutter-cleaning/oakville': typeof GutterCleaningOakvilleRoute
  '/gutter-cleaning/oshawa': typeof GutterCleaningOshawaRoute
  '/gutter-cleaning/pickering': typeof GutterCleaningPickeringRoute
  '/gutter-cleaning/richmond-hill': typeof GutterCleaningRichmondHillRoute
  '/gutter-cleaning/scarborough': typeof GutterCleaningScarboroughRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/gutter-cleaning/vaughan': typeof GutterCleaningVaughanRoute
  '/gutter-cleaning/whitby': typeof GutterCleaningWhitbyRoute
  '/junk-removal/markham': typeof JunkRemovalMarkhamRoute
  '/junk-removal/mississauga': typeof JunkRemovalMississaugaRoute
  '/junk-removal/toronto': typeof JunkRemovalTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning': typeof GutterCleaningIndexRoute
  '/junk-removal': typeof JunkRemovalIndexRoute
  '/pressure-washing': typeof PressureWashingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gutter-cleaning/ajax': typeof GutterCleaningAjaxRoute
  '/gutter-cleaning/brampton': typeof GutterCleaningBramptonRoute
  '/gutter-cleaning/burlington': typeof GutterCleaningBurlingtonRoute
  '/gutter-cleaning/etobicoke': typeof GutterCleaningEtobicokeRoute
  '/gutter-cleaning/markham': typeof GutterCleaningMarkhamRoute
  '/gutter-cleaning/mississauga': typeof GutterCleaningMississaugaRoute
  '/gutter-cleaning/north-york': typeof GutterCleaningNorthYorkRoute
  '/gutter-cleaning/oakville': typeof GutterCleaningOakvilleRoute
  '/gutter-cleaning/oshawa': typeof GutterCleaningOshawaRoute
  '/gutter-cleaning/pickering': typeof GutterCleaningPickeringRoute
  '/gutter-cleaning/richmond-hill': typeof GutterCleaningRichmondHillRoute
  '/gutter-cleaning/scarborough': typeof GutterCleaningScarboroughRoute
  '/gutter-cleaning/toronto': typeof GutterCleaningTorontoRoute
  '/gutter-cleaning/vaughan': typeof GutterCleaningVaughanRoute
  '/gutter-cleaning/whitby': typeof GutterCleaningWhitbyRoute
  '/junk-removal/markham': typeof JunkRemovalMarkhamRoute
  '/junk-removal/mississauga': typeof JunkRemovalMississaugaRoute
  '/junk-removal/toronto': typeof JunkRemovalTorontoRoute
  '/pressure-washing/markham': typeof PressureWashingMarkhamRoute
  '/pressure-washing/mississauga': typeof PressureWashingMississaugaRoute
  '/pressure-washing/toronto': typeof PressureWashingTorontoRoute
  '/gutter-cleaning/': typeof GutterCleaningIndexRoute
  '/junk-removal/': typeof JunkRemovalIndexRoute
  '/pressure-washing/': typeof PressureWashingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/ajax'
    | '/gutter-cleaning/brampton'
    | '/gutter-cleaning/burlington'
    | '/gutter-cleaning/etobicoke'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/north-york'
    | '/gutter-cleaning/oakville'
    | '/gutter-cleaning/oshawa'
    | '/gutter-cleaning/pickering'
    | '/gutter-cleaning/richmond-hill'
    | '/gutter-cleaning/scarborough'
    | '/gutter-cleaning/toronto'
    | '/gutter-cleaning/vaughan'
    | '/gutter-cleaning/whitby'
    | '/junk-removal/markham'
    | '/junk-removal/mississauga'
    | '/junk-removal/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning/'
    | '/junk-removal/'
    | '/pressure-washing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/ajax'
    | '/gutter-cleaning/brampton'
    | '/gutter-cleaning/burlington'
    | '/gutter-cleaning/etobicoke'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/north-york'
    | '/gutter-cleaning/oakville'
    | '/gutter-cleaning/oshawa'
    | '/gutter-cleaning/pickering'
    | '/gutter-cleaning/richmond-hill'
    | '/gutter-cleaning/scarborough'
    | '/gutter-cleaning/toronto'
    | '/gutter-cleaning/vaughan'
    | '/gutter-cleaning/whitby'
    | '/junk-removal/markham'
    | '/junk-removal/mississauga'
    | '/junk-removal/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning'
    | '/junk-removal'
    | '/pressure-washing'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/gutter-cleaning/ajax'
    | '/gutter-cleaning/brampton'
    | '/gutter-cleaning/burlington'
    | '/gutter-cleaning/etobicoke'
    | '/gutter-cleaning/markham'
    | '/gutter-cleaning/mississauga'
    | '/gutter-cleaning/north-york'
    | '/gutter-cleaning/oakville'
    | '/gutter-cleaning/oshawa'
    | '/gutter-cleaning/pickering'
    | '/gutter-cleaning/richmond-hill'
    | '/gutter-cleaning/scarborough'
    | '/gutter-cleaning/toronto'
    | '/gutter-cleaning/vaughan'
    | '/gutter-cleaning/whitby'
    | '/junk-removal/markham'
    | '/junk-removal/mississauga'
    | '/junk-removal/toronto'
    | '/pressure-washing/markham'
    | '/pressure-washing/mississauga'
    | '/pressure-washing/toronto'
    | '/gutter-cleaning/'
    | '/junk-removal/'
    | '/pressure-washing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GutterCleaningAjaxRoute: typeof GutterCleaningAjaxRoute
  GutterCleaningBramptonRoute: typeof GutterCleaningBramptonRoute
  GutterCleaningBurlingtonRoute: typeof GutterCleaningBurlingtonRoute
  GutterCleaningEtobicokeRoute: typeof GutterCleaningEtobicokeRoute
  GutterCleaningMarkhamRoute: typeof GutterCleaningMarkhamRoute
  GutterCleaningMississaugaRoute: typeof GutterCleaningMississaugaRoute
  GutterCleaningNorthYorkRoute: typeof GutterCleaningNorthYorkRoute
  GutterCleaningOakvilleRoute: typeof GutterCleaningOakvilleRoute
  GutterCleaningOshawaRoute: typeof GutterCleaningOshawaRoute
  GutterCleaningPickeringRoute: typeof GutterCleaningPickeringRoute
  GutterCleaningRichmondHillRoute: typeof GutterCleaningRichmondHillRoute
  GutterCleaningScarboroughRoute: typeof GutterCleaningScarboroughRoute
  GutterCleaningTorontoRoute: typeof GutterCleaningTorontoRoute
  GutterCleaningVaughanRoute: typeof GutterCleaningVaughanRoute
  GutterCleaningWhitbyRoute: typeof GutterCleaningWhitbyRoute
  JunkRemovalMarkhamRoute: typeof JunkRemovalMarkhamRoute
  JunkRemovalMississaugaRoute: typeof JunkRemovalMississaugaRoute
  JunkRemovalTorontoRoute: typeof JunkRemovalTorontoRoute
  PressureWashingMarkhamRoute: typeof PressureWashingMarkhamRoute
  PressureWashingMississaugaRoute: typeof PressureWashingMississaugaRoute
  PressureWashingTorontoRoute: typeof PressureWashingTorontoRoute
  GutterCleaningIndexRoute: typeof GutterCleaningIndexRoute
  JunkRemovalIndexRoute: typeof JunkRemovalIndexRoute
  PressureWashingIndexRoute: typeof PressureWashingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/': {
      id: '/pressure-washing/'
      path: '/pressure-washing'
      fullPath: '/pressure-washing/'
      preLoaderRoute: typeof PressureWashingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-removal/': {
      id: '/junk-removal/'
      path: '/junk-removal'
      fullPath: '/junk-removal/'
      preLoaderRoute: typeof JunkRemovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/': {
      id: '/gutter-cleaning/'
      path: '/gutter-cleaning'
      fullPath: '/gutter-cleaning/'
      preLoaderRoute: typeof GutterCleaningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/toronto': {
      id: '/pressure-washing/toronto'
      path: '/pressure-washing/toronto'
      fullPath: '/pressure-washing/toronto'
      preLoaderRoute: typeof PressureWashingTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/mississauga': {
      id: '/pressure-washing/mississauga'
      path: '/pressure-washing/mississauga'
      fullPath: '/pressure-washing/mississauga'
      preLoaderRoute: typeof PressureWashingMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing/markham': {
      id: '/pressure-washing/markham'
      path: '/pressure-washing/markham'
      fullPath: '/pressure-washing/markham'
      preLoaderRoute: typeof PressureWashingMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-removal/toronto': {
      id: '/junk-removal/toronto'
      path: '/junk-removal/toronto'
      fullPath: '/junk-removal/toronto'
      preLoaderRoute: typeof JunkRemovalTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-removal/mississauga': {
      id: '/junk-removal/mississauga'
      path: '/junk-removal/mississauga'
      fullPath: '/junk-removal/mississauga'
      preLoaderRoute: typeof JunkRemovalMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-removal/markham': {
      id: '/junk-removal/markham'
      path: '/junk-removal/markham'
      fullPath: '/junk-removal/markham'
      preLoaderRoute: typeof JunkRemovalMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/whitby': {
      id: '/gutter-cleaning/whitby'
      path: '/gutter-cleaning/whitby'
      fullPath: '/gutter-cleaning/whitby'
      preLoaderRoute: typeof GutterCleaningWhitbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/vaughan': {
      id: '/gutter-cleaning/vaughan'
      path: '/gutter-cleaning/vaughan'
      fullPath: '/gutter-cleaning/vaughan'
      preLoaderRoute: typeof GutterCleaningVaughanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/toronto': {
      id: '/gutter-cleaning/toronto'
      path: '/gutter-cleaning/toronto'
      fullPath: '/gutter-cleaning/toronto'
      preLoaderRoute: typeof GutterCleaningTorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/scarborough': {
      id: '/gutter-cleaning/scarborough'
      path: '/gutter-cleaning/scarborough'
      fullPath: '/gutter-cleaning/scarborough'
      preLoaderRoute: typeof GutterCleaningScarboroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/richmond-hill': {
      id: '/gutter-cleaning/richmond-hill'
      path: '/gutter-cleaning/richmond-hill'
      fullPath: '/gutter-cleaning/richmond-hill'
      preLoaderRoute: typeof GutterCleaningRichmondHillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/pickering': {
      id: '/gutter-cleaning/pickering'
      path: '/gutter-cleaning/pickering'
      fullPath: '/gutter-cleaning/pickering'
      preLoaderRoute: typeof GutterCleaningPickeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/oshawa': {
      id: '/gutter-cleaning/oshawa'
      path: '/gutter-cleaning/oshawa'
      fullPath: '/gutter-cleaning/oshawa'
      preLoaderRoute: typeof GutterCleaningOshawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/oakville': {
      id: '/gutter-cleaning/oakville'
      path: '/gutter-cleaning/oakville'
      fullPath: '/gutter-cleaning/oakville'
      preLoaderRoute: typeof GutterCleaningOakvilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/north-york': {
      id: '/gutter-cleaning/north-york'
      path: '/gutter-cleaning/north-york'
      fullPath: '/gutter-cleaning/north-york'
      preLoaderRoute: typeof GutterCleaningNorthYorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/mississauga': {
      id: '/gutter-cleaning/mississauga'
      path: '/gutter-cleaning/mississauga'
      fullPath: '/gutter-cleaning/mississauga'
      preLoaderRoute: typeof GutterCleaningMississaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/markham': {
      id: '/gutter-cleaning/markham'
      path: '/gutter-cleaning/markham'
      fullPath: '/gutter-cleaning/markham'
      preLoaderRoute: typeof GutterCleaningMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/etobicoke': {
      id: '/gutter-cleaning/etobicoke'
      path: '/gutter-cleaning/etobicoke'
      fullPath: '/gutter-cleaning/etobicoke'
      preLoaderRoute: typeof GutterCleaningEtobicokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/burlington': {
      id: '/gutter-cleaning/burlington'
      path: '/gutter-cleaning/burlington'
      fullPath: '/gutter-cleaning/burlington'
      preLoaderRoute: typeof GutterCleaningBurlingtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/brampton': {
      id: '/gutter-cleaning/brampton'
      path: '/gutter-cleaning/brampton'
      fullPath: '/gutter-cleaning/brampton'
      preLoaderRoute: typeof GutterCleaningBramptonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutter-cleaning/ajax': {
      id: '/gutter-cleaning/ajax'
      path: '/gutter-cleaning/ajax'
      fullPath: '/gutter-cleaning/ajax'
      preLoaderRoute: typeof GutterCleaningAjaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GutterCleaningAjaxRoute: GutterCleaningAjaxRoute,
  GutterCleaningBramptonRoute: GutterCleaningBramptonRoute,
  GutterCleaningBurlingtonRoute: GutterCleaningBurlingtonRoute,
  GutterCleaningEtobicokeRoute: GutterCleaningEtobicokeRoute,
  GutterCleaningMarkhamRoute: GutterCleaningMarkhamRoute,
  GutterCleaningMississaugaRoute: GutterCleaningMississaugaRoute,
  GutterCleaningNorthYorkRoute: GutterCleaningNorthYorkRoute,
  GutterCleaningOakvilleRoute: GutterCleaningOakvilleRoute,
  GutterCleaningOshawaRoute: GutterCleaningOshawaRoute,
  GutterCleaningPickeringRoute: GutterCleaningPickeringRoute,
  GutterCleaningRichmondHillRoute: GutterCleaningRichmondHillRoute,
  GutterCleaningScarboroughRoute: GutterCleaningScarboroughRoute,
  GutterCleaningTorontoRoute: GutterCleaningTorontoRoute,
  GutterCleaningVaughanRoute: GutterCleaningVaughanRoute,
  GutterCleaningWhitbyRoute: GutterCleaningWhitbyRoute,
  JunkRemovalMarkhamRoute: JunkRemovalMarkhamRoute,
  JunkRemovalMississaugaRoute: JunkRemovalMississaugaRoute,
  JunkRemovalTorontoRoute: JunkRemovalTorontoRoute,
  PressureWashingMarkhamRoute: PressureWashingMarkhamRoute,
  PressureWashingMississaugaRoute: PressureWashingMississaugaRoute,
  PressureWashingTorontoRoute: PressureWashingTorontoRoute,
  GutterCleaningIndexRoute: GutterCleaningIndexRoute,
  JunkRemovalIndexRoute: JunkRemovalIndexRoute,
  PressureWashingIndexRoute: PressureWashingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
